name: Update stats

on:
  schedule:
    - cron: "0 11 * * *"
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@master
        with:
          token: ${{ secrets.USER_TOKEN }}
      - name: Update README.md
        shell: bash
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name 'Ufuk'
            git config user.email 'ufuayk@gmail.com'
            git add *.md
            git commit -m "Update README.md"
            git push
          fi
