name: Blog

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest posts from my blog.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git identity
        run: |
          git config --global user.name "Ufuk"
          git config --global user.email "ufuayk@users.noreply.github.com"

      - name: Run blog-post-workflow without committing
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST"
          feed_list: "https://ufuk.bearblog.dev/feed/?type=rss"

      - name: Commit changes manually if any
        run: |
          git add README.md
          git diff --cached --quiet
          git commit -m "readme update"
          git push
